---
title: "STAT 345 Final Project - Real Estate"
author: "STAT 345 - Braden Barglind, Adam Steckbauer, Stephen Koch, Douglas Klister"
output: html_document
---

Expected Submission: You will generate a well-written R Markdown report that addresses the following prompts. This R Markdown report should source your analysis code and only display top-level, abstracted code _if/when appropriate_. Choices made during the analysis project should be described and justified in the report. You will present on your results during the final exam period for the semester. The written report (knitted file), presentation file, and your analysis code should be submitted to D2L by Tuesday, May 14 at 12:15pm. 

**General advice:** Get started early. If you wait to the last minute, it will not go well. For this project, you may find yourself spending a reasonable amount of time _searching_ for help.

1. _Rules!_ Monopoly has several rules related to movement around the game board. Movement is affected by standard dice rolls, special conditions for some dice rolls, and game cards. Find and summarize these rules. 

2. _Let's Get Moving_ Build a system that allows for up to 4 players to move around the game board. As a first attempt, focus on standard dice rolls, ignoring additional rules related to rolling doubles, jail, or special cards. Which properties are landed on most frequently? Create a visualization for this!

3. _Double Down_ Improve your system to incorporate going to jail, including the doubles-rolling condition. Which properties are landed on most frequently now? Has this changed dramatically from the previous system (that didn't account for jail)? Again, visualize this!

4. _Take a Chance_ Incorporate the movement cards into your system. You can ignore the effects of non-movement cards, but not their existence! Which properties are landed on most frequently now? Has this changed dramatically from the previous system (that didn't account for Chance)? Again, visualize this!

5. _Play a Game_ Extend your system to allow for up to 4 players to "play" the game. You may choose a reasonable starting board and player money level (so, you don't have to buy properties). Include payments between players, payments to the bank, and payments from the bank (there are several cards that will effect these that you should account for). You do not need to consider mortgaging properties (so a player loses when their liquid cash has run out). How long do games typically last given your starting board and money level? How does this change if money paid to the bank is placed in "Free Parking" and awarded to players landing on that space?

******************
#Vectorized approach instead of Excel File
monopoly_board <- data.frame(space = 1:45, title = c("Go", "Mediterranean Avenue", "Community Chest 1", "Baltic Avenue", "Income Tax", "Reading Railroad", "Oriental Avenue", "Chance 1", "Vermont Avenue", "Connecticut Avenue", "Jail", "St. Charles Place", "Electric Company", "States Avenue", "Virginia Avenue", "Pennsylvania Railroad", "St. James Place", "Community Chest 2", "Tennessee Avenue", "New York Avenue", "Free Parking", "Kentucky Avenue", "Chance 2", "Indiana Avenue", "Illinois Avenue", "B. & O. Railroad", "Atlantic Avenue", "Ventnor Avenue", "Water Works", "Marvin Gardens", "Go to Jail", "Pacific Avenue", "{North Carolina Avenue", "Community Chest 3", "Pennsylvania Avenue", "Short Line", "Chance 3", "Park Place", "Luxury Tax", "Boardwalk", "Go to Jail", "N", "N", "N", "N", "N"), stringsAsFactors = FALSE)
chance_cards <- data.frame(index = 1:15, card = c("Advance to Go", "Advance to Illinois Ave - If you pass Go, collect $200", "Advance to St. Charles Place – If you pass Go, collect $200", "Advance token to nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total ten times the amount thrown.", "Advance token to the nearest Railroad and pay owner twice the rental to which he/she {he} is otherwise entitled. If Railroad is unowned, you may buy it from the Bank.", "Bank pays you dividend of $50", "Get Out of Jail Free", "Go Back 3 Spaces", "Go to Jail–Go directly to Jail–Do not pass Go, do not collect $200", "Make general repairs on all your property–For each house pay $25–For each hotel $100", "Pay poor tax of $15", "Take a trip to Reading Railroad–If you pass Go, collect $200", "Take a walk on the Boardwalk–Advance token to Boardwalk", "You have been elected Chairman of the Board–Pay each player $50", "Your building and loan matures—Collect $150", "You have won a crossword competition—Collect $100"))
 

#Creating the Dice Rolls
dice <- function(verbose = FALSE){
  faces <- sample(1:6,2, replace = TRUE)
  if(faces[1] == faces[2]) doubles = TRUE
  else doubles = FALSE
  movement = sum(faces)
  if(verbose) cat("Rolled:", faces[1], faces[2], "/n")
  return(list(faces=faces, doubles=doubles, movement=movement))
  
#Creating the Player(s)
player <- setRefClass("player", fields = list(pos="numeric", verbose='logical'), method = list(move_n = function(n){}, go_2_space_n = function(n){}, trap = function(n){}, getout = function(n){}, gotojail = function(n){}))

#Tracking the Player's Movements
tracking <- setRefClass("tracking", fields = list(tally = "numeric"), methods = list(increase_count = function(n){tally[n] <<- tally[n] + 1}))

checkchance <- function(player, tracking){}
checkcommunity <- function(player, tracking){}
taketurn <- function(player, tracking){}
set.seed(12345)
space_tracking <- tracking$new(tally = rep(0,40))

#Simulating game with 4 players
for(i in 1:1000){
  player1 <- player$new(pos = 1, verbose = FALSE)
  player2 <- player$new(pos = 1, verbose = FALSE)
  player3 <- player$new(pos = 1, verbose = FALSE)
  player4 <- player$new(pos = 1, verbose = FALSE)
  for(i in 1:150){
    if(player1$verbose) cat("Player 1 turn\n")
    taketurn(player1, space_tracking)
    if(player2$verbose) cat("Player 2 turn\n")
    taketurn(player1, space_tracking)
    if(player3$verbose) cat("Player 3 turn\n")
    taketurn(player1, space_tracking)
    if(player4$verbose) cat("Player 4 turn\n")
    taketurn(player1, space_tracking)
  }
}





